#!/bin/sh
# One-shot: registers this workshop's Forgejo Actions runner and writes its
# config.yaml to the shared dns_runner_config volume, which forgejo-runner
# (see ../docker-compose.override.yml) then starts from. Idempotent: skips
# straight to "done" if that config.yaml already exists, same pattern as
# engine/git-server/bootstrap.sh.
#
# Runs the *server-side* `forgejo forgejo-cli actions register` CLI (same
# image/volume access as bootstrap.sh's `forgejo admin user create`) rather
# than the runner's own interactive `register` handshake - it lets us
# choose the shared secret ourselves instead of copying a token out of a
# one-time CLI/UI flow, which is what makes this whole step scriptable.
set -eu

forgejo_config="/data/gitea/conf/app.ini"
runner_config_dir="/runner-config"
runner_config="${runner_config_dir}/config.yaml"
runner_secret_file="${runner_config_dir}/.secret"

org="${FORGEJO_ORG:?Set FORGEJO_ORG}"
repo="${FORGEJO_REPO:?Set FORGEJO_REPO}"
runner_name="${DNS_RUNNER_NAME:-dns-as-code-runner}"

log() { printf '[runner-setup] %s\n' "$1"; }

if [ -f "$runner_config" ]; then
  log "config already exists at ${runner_config} - nothing to do"
  exit 0
fi

mkdir -p "$runner_config_dir"

if [ ! -f "$runner_secret_file" ]; then
  log "generating runner secret"
  # 20 random bytes -> 40 hex chars, the length forgejo-cli actions
  # register expects. Not attacker-facing: this only authenticates the
  # runner to this lab's own internal-only Forgejo instance.
  head -c 20 /dev/urandom | od -An -tx1 | tr -d ' \n' > "$runner_secret_file"
  chmod 600 "$runner_secret_file"
fi
secret="$(cat "$runner_secret_file")"

log "registering runner '${runner_name}' scoped to ${org}/${repo}"
register_output="$(forgejo forgejo-cli actions register \
  --config "$forgejo_config" \
  --name "$runner_name" \
  --scope "${org}/${repo}" \
  --secret "$secret")"

uuid="$(printf '%s' "$register_output" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)"
if [ -z "$uuid" ]; then
  echo "[runner-setup] error: could not find a runner UUID in the register output below:" >&2
  echo "$register_output" >&2
  exit 1
fi
log "registered, uuid=${uuid}"

tmp="$(mktemp)"
cat > "$tmp" <<EOF
# Generated by compose/runner/register.sh - do not edit by hand, this file
# is regenerated (only if missing) every 'run.sh dns-as-code'.
log:
  level: info
  job_level: info

runner:
  capacity: 1
  # The "host" schema (no "://arg" - that's only for docker/lxc, which take
  # an image) runs job steps directly in this container's own filesystem -
  # no docker executor, no docker.sock mount. See ../runner/Dockerfile for
  # why (this container has dnscontrol/git/curl/jq preinstalled instead).
  labels:
    - "host:host"

cache:
  enabled: false

container:
  docker_host: "-"

server:
  connections:
    dns-lab:
      url: http://git-server:3000/
      uuid: ${uuid}
      token: ${secret}
EOF
mv "$tmp" "$runner_config"
log "wrote ${runner_config}"
