#!/usr/bin/env python3
"""Rebuild modules/achievements/service/static/mapdata.js from Natural Earth (public domain).

Run by hand, only when the map outline should change (the output is committed, so nothing at
runtime or in a build needs the network):

    python3 -B modules/achievements/tools/build_map_data.py

Downloads 110m land (the world), 50m land + lakes + land boundaries (the Canada/US inset, clipped
to INSET) from https://github.com/nvkelso/natural-earth-vector, simplifies them, and writes
`window.DOJO_MAP` with coordinates as integer hundredths of a degree, flat [lon, lat, lon, lat...].
Natural Earth: https://www.naturalearthdata.com/ (public domain, no attribution required).
"""
import json
import os
import urllib.request

BASE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "service", "static", "mapdata.js")
INSET = (-135.0, 27.0, -50.0, 70.0)     # lon0, lat0, lon1, lat1: Canada, the lakes and the northern US


def fetch(name):
    with urllib.request.urlopen(BASE + name + ".geojson", timeout=60) as r:
        return json.load(r)


def rings_of(geom):
    if geom["type"] == "Polygon":
        return list(geom["coordinates"])
    if geom["type"] == "MultiPolygon":
        return [r for poly in geom["coordinates"] for r in poly]
    if geom["type"] == "LineString":
        return [geom["coordinates"]]
    if geom["type"] == "MultiLineString":
        return list(geom["coordinates"])
    return []


def dp(pts, tol):
    """Douglas-Peucker (iterative). A closed ring is split at its farthest point first."""
    if len(pts) < 3:
        return pts
    if pts[0] == pts[-1]:
        m = max(range(1, len(pts) - 1), key=lambda i: (pts[i][0] - pts[0][0]) ** 2 + (pts[i][1] - pts[0][1]) ** 2)
        return dp(pts[:m + 1], tol)[:-1] + dp(pts[m:], tol)
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        (ax, ay), (bx, by) = pts[a], pts[b]
        dx, dy = bx - ax, by - ay
        norm = (dx * dx + dy * dy) ** 0.5 or 1e-12
        best, idx = -1.0, None
        for i in range(a + 1, b):
            d = abs(dy * (pts[i][0] - ax) - dx * (pts[i][1] - ay)) / norm
            if d > best:
                best, idx = d, i
        if best > tol and idx is not None:
            keep[idx] = True
            stack += [(a, idx), (idx, b)]
    return [p for p, k in zip(pts, keep) if k]


def inside(p, box, margin=0.0):
    return box[0] - margin <= p[0] <= box[2] + margin and box[1] - margin <= p[1] <= box[3] + margin


def clip_runs(pts, box):
    """Keep points inside BOX (with margin) and one neighbour either side, so an outline that
    leaves the box is cut short instead of shipping continents the inset never draws."""
    flags = [inside(p, box, 3.0) for p in pts]
    return [p for i, p in enumerate(pts)
            if flags[i] or (i and flags[i - 1]) or (i + 1 < len(pts) and flags[i + 1])]


def pack(pts):
    out = []
    for lon, lat in pts:
        out += [round(lon * 100), round(lat * 100)]
    return out


def collect(name, tol, box=None, min_extent=0.0, closed=True):
    rings = []
    for f in fetch(name)["features"]:
        for ring in rings_of(f["geometry"]):
            pts = [(p[0], p[1]) for p in ring]
            xs, ys = [p[0] for p in pts], [p[1] for p in pts]
            if box and (max(xs) < box[0] - 3 or min(xs) > box[2] + 3 or max(ys) < box[1] - 3 or min(ys) > box[3] + 3):
                continue
            if max(max(xs) - min(xs), max(ys) - min(ys)) < min_extent:
                continue
            if box:
                pts = clip_runs(pts, box)
            pts = dp(pts, tol)
            if len(pts) >= (3 if closed else 2):
                rings.append(pack(pts))
    return rings


def main():
    data = {
        "world": collect("ne_110m_land", 0.08, min_extent=0.0),
        "inset_box": list(INSET),
        "land": collect("ne_50m_land", 0.03, INSET, min_extent=0.3),
        "lakes": collect("ne_50m_lakes", 0.03, INSET, min_extent=1.5),
        "borders": collect("ne_50m_admin_0_boundary_lines_land", 0.03, INSET, min_extent=0.5, closed=False),
    }
    text = ("// Natural Earth (public domain) outline; generated by modules/achievements/tools/build_map_data.py.\n"
            "// Rings are flat [lon, lat, ...] in integer hundredths of a degree.\n"
            "window.DOJO_MAP = " + json.dumps(data, separators=(",", ":")) + ";\n")
    with open(OUT, "w") as f:
        f.write(text)
    print("wrote", os.path.normpath(OUT), len(text) // 1024, "KB")


if __name__ == "__main__":
    main()
