#!/usr/bin/env python3
"""Generate a workshop's ACHIEVEMENTS.md from its modular catalog.

    python3 -B render_md.py workshops/git-fundamentals            # write ACHIEVEMENTS.md
    python3 -B render_md.py workshops/git-fundamentals --check    # exit 1 if it is stale
    python3 -B render_md.py --all [--check]                       # every workshop with a catalog

The markdown is a review copy; the JSON is the source. A unit test runs --check --all, so a
catalog edit without a regenerated ACHIEVEMENTS.md fails the tests.
"""

import os
import sys

import catalog as cat

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
SHARED = os.path.join(HERE, "shared.json")


def _cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def _read(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as fh:
        return fh.read().rstrip("\n")


def _core_cell(m):
    if m["core"]:
        return "yes"
    return f"no ({m['note']})" if m.get("note") else "no"


def _milestone_table(items):
    rows = ["| ID | Title | Joke | Pts | Core | When |", "|---|---|---|---|---|---|"]
    for m in items:
        if m.get("retired"):
            continue
        rows.append("| {} | {} | \"{}\" | {} | {} | {} |".format(
            m["id"], _cell(m["title"]), _cell(m["joke"]), cat.points_of(m, "milestone"),
            _core_cell(m), _cell(m["when"])))
    return rows


def _funny_table(items):
    rows = ["| ID | Title | Joke | Pts | When |", "|---|---|---|---|---|"]
    for m in items:
        if m.get("retired"):
            continue
        rows.append("| {} | {} | \"{}\" | {} | {} |".format(
            m["id"], _cell(m["title"]), _cell(m["joke"]), cat.points_of(m, "funny"), _cell(m["when"])))
    return rows


def _challenge_block(ch, level):
    head = "#" * level
    after = f" ({ch['after']})" if ch.get("after") else ""
    out = [f"{head} {ch['id'].upper()}: {ch['title']}{after}", ""]
    out.append(f"- **Points:** {cat.points_of(ch, 'capstone' if ch['id'] == 'capstone' else 'challenge')}")
    out.append(f"- **Where it runs:** {ch['space']}")
    out.append(f"- **Goal shown to the student:** {ch['goal']}")
    if ch.get("constraints"):
        out.append(f"- **Constraints:** {ch['constraints']}")
    if ch.get("seed"):
        out.append(f"- **Seed:** {ch['seed']}")
    out.append(f"- **Verify:** {ch['verify_text']}")
    out.append(f"- **Hint 1:** {ch['hints'][0]}")
    out.append(f"- **Hint 2:** {ch['hints'][1]}")
    if ch.get("answer"):
        out.append(f"- **Answer:** {ch['answer']}")
    if ch.get("isolation"):
        out.append(f"- **Collision check:** {ch['isolation']}")
    if ch.get("facilitator"):
        out.append("- **Needs the facilitator:** yes")
    if ch.get("badge_tier"):
        out.append(f"- **Badge tier:** {ch['badge_tier']} (stars)")
    return out


def render(catalog):
    name = catalog["workshop"]
    out = [f"# {name}: achievements catalog", ""]
    out.append(
        "Generated from `achievements/` beside this file by `modules/achievements/catalog/render_md.py`. "
        "Do not edit this file: edit the JSON and run the script (a unit test fails when this copy is stale).")
    out.append("")
    out.append(_read("how_to_read.md"))
    out.append("")
    if catalog["intro"].strip():
        out.append(catalog["intro"].strip())
        out.append("")
    out.append(_read("rules.md"))
    out.append("")
    for lab in catalog["labs"]:
        out.append(f"## {lab['id'].replace('lab', 'Lab ')}: {lab['title']}")
        out.append("")
        out.extend(_milestone_table(lab["milestones"]))
        out.append("")
    out.append("## Funny unlocks (5 points, any time)")
    out.append("")
    out.extend(_funny_table(catalog["funny"]))
    out.append("")
    out.append("(The cheating and \"bumped into your neighbour\" unlocks are shared across every workshop, so they live "
               "with the module, not here.)")
    out.append("")
    out.append("## Challenges (100 points, optional, no steps given)")
    out.append("")
    out.append("Each has two hints (25% each by default) and an answer that scores zero. The check is by outcome, so "
               "any way of doing it counts.")
    out.append("")
    if catalog["challenges_intro"].strip():
        out.append(catalog["challenges_intro"].strip())
        out.append("")
    for ch in catalog["challenges"]:
        if ch.get("retired"):
            continue
        out.extend(_challenge_block(ch, 3))
        out.append("")
    cap = catalog["capstone"]
    out.append(f"## Capstone ({cat.points_of(cap, 'capstone')} points, optional): {cap['title']}")
    out.append("")
    out.extend(_challenge_block(cap, 3)[2:])
    out.append("")
    core = cat.core_milestones(catalog)
    ms = cat.milestones(catalog)
    funny = [f for f in catalog["funny"] if not f.get("retired")]
    chs = [c for c in catalog["challenges"] if not c.get("retired")]
    core_pts = sum(cat.points_of(m, "milestone") for m in core)
    all_ms_pts = sum(cat.points_of(m, "milestone") for m in ms)
    funny_pts = sum(cat.points_of(f, "funny") for f in funny)
    ch_pts = sum(cat.points_of(c, "challenge") for c in chs)
    cap_pts = cat.points_of(cap, "capstone")
    out.append("## Totals (computed)")
    out.append("")
    out.append(f"{len(core)} core milestones ({core_pts} points) of {len(ms)} milestones ({all_ms_pts}) · "
               f"{len(funny)} funny unlocks (up to {funny_pts}) · {len(chs)} challenges ({ch_pts}) · "
               f"capstone {cap_pts} · plus first blood and class-clear bonuses. "
               f"Everything: {all_ms_pts + funny_pts + ch_pts + cap_pts} points.")
    return "\n".join(out) + "\n"


def workshop_dirs():
    root = os.path.join(REPO, "workshops")
    return [os.path.join(root, d) for d in sorted(os.listdir(root))
            if os.path.isfile(os.path.join(root, d, "achievements", "catalog.json"))]


def main(argv):
    check = "--check" in argv
    args = [a for a in argv if not a.startswith("--")]
    dirs = workshop_dirs() if "--all" in argv else args
    if not dirs:
        print(__doc__, file=sys.stderr)
        return 2
    stale = 0
    for d in dirs:
        try:
            catalog, warnings = cat.load(d, SHARED)
        except cat.CatalogError as exc:
            print(f"{d}: catalog errors:\n  " + "\n  ".join(exc.problems), file=sys.stderr)
            return 1
        for w in warnings:
            if "--quiet" not in argv:
                print(f"warning: {w}", file=sys.stderr)
        text = render(catalog)
        path = os.path.join(d, "ACHIEVEMENTS.md")
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as fh:
                current = fh.read()
        if check:
            if current != text:
                print(f"stale: {path} (run render_md.py {os.path.relpath(d, REPO)})", file=sys.stderr)
                stale += 1
        elif current != text:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(text)
            print(f"wrote {path}")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
